### ISSUE TITLE
[Add FEATURE] Add filter to timeline card

### ISSUE THREAD

**Issue by Shaun-Harrison** [valentinfrlch/llmvision-card#12]
I've been able to add multiple timeline entities via the integration. Looking at the timeline card, it's possible to state what calendar to display, but what seems to be missing, is when you use the ['remember' service](https://llm-vision.gitbook.io/getting-started/usage/remember) is a way to state what timeline to save too

My use case is to have one timeline for vehicles and one for people

**Comment by redford-jones** [comment]
I did start to take a look at this myself last week. My use case was to add a camera_entity filter to the card config and filter out events in the timeline that don't contain the configured camera_entity. I got distracted by the Gemini consumption issue on the main integration however.

I shall try to set some time aside this week to take another look.

**Comment by ijustlikeit** [comment]
I have a way to display the events from the events.db in a way that filters and allows you to customize the list to your liking.  Can be found here:  https://github.com/ijustlikeit/grafana-llm-vision-events

**Comment by valentinfrlch** [comment]
I have implemented some filters with some additional improvements (like a visual editor):

<img width="474" alt="Image" src="https://github.com/user-attachments/assets/fb72fb25-10ab-4992-bc7d-159b448aea18" />

The changes are live in the [latest alpha](https://github.com/valentinfrlch/llmvision-card/releases/tag/v1.4.3-alpha.4). I have been using the alpha for a couple days now and don't have any issues with it. Feel free to try it out and give feedback. There should also be a beta in a few days.

**Comment by redford-jones** [comment]
Thanks @valentinfrlch, testing the alpha now. 
One observation - I have a timeline entry which doesn't have a camera entity associated (problem with my automation, it's not populating the camera entity, which is supposed to be derived from a template of the area associated to an alarm sensor). 
When I filter to a single camera on the timeline card (in this scenario `camera.doorbell`), it filters by that entity but the event with no camera associated is also visible in the timeline card.

**Comment by Shaun-Harrison** [comment]
Testing now, is working but have got a potential issue

This is my code 

```
          - type: custom:llmvision-card
            calendar_entity: calendar.llm_vision_timeline
            number_of_events: 5
            refresh_interval: 1
            category_filters:
              - people
            custom_colors:
              people:
                - 251
                - 255
                - 0
          - type: custom:llmvision-card
            calendar_entity: calendar.llm_vision_timeline
            number_of_events: 5
            refresh_interval: 1
            category_filters:
              - vehicles
            custom_colors:
              vehicles:
                - 143
                - 143
                - 143
```

However, I'm only getting 4 events for vehicles instead of the expected 5

And if I'm being super cheeky, would there be a way to have a `visitor` filter? When someone actually presses my doorbell its categorized as a visitor 

Thanks for the amazing work with this! the Colours are a nice touch
