### ISSUE TITLE
Deafult Settings Card, Bad Docs.

### ISSUE THREAD

**Issue by milandzuris** [valentinfrlch/llmvision-card#2]
Hi, whats the default Action (call_service) for Card so that showing new Events?, just tick only Generate Title?.
Blueprint or Automation to update the calendar entity, where is Blueprint?, and what automation do you mean for this?.
Card need better Docs, but thx for your work.

**Comment by valentinfrlch** [comment]
Thanks for the feedback. The docs will be improved until the public release.

There are two ways to add events to the Timeline:
1. `remember`: This is a **parameter** present in `image`, `video` and `stream` analyzers. You will also need to enable `generate_title` and `expose_images` and `expose_images_persist` to generate a title for the event and expose the key frame as preview respectively.
2. You can add custom events (without using LLM Vision analyzers) to the Timeline using the `remember` **action**.

Currently you will have to use the beta blueprint [here](https://raw.githubusercontent.com/valentinfrlch/ha-llmvision/refs/heads/main/blueprints/event_summary_beta.yaml).

**Comment by milandzuris** [comment]
> Thanks for the feedback. The docs will be improved until the public release.
> 
> There are two ways to add events to the Timeline:
> 
> 1. `remember`: This is a **parameter** present in `image`, `video` and `stream` analyzers. You will also need to enable `generate_title` and `expose_images` and `expose_images_persist` to generate a title for the event and expose the key frame as preview respectively.
> 2. You can add custom events (without using LLM Vision analyzers) to the Timeline using the `remember` **action**.
> 
> Currently you will have to use the beta blueprint [here](https://raw.githubusercontent.com/valentinfrlch/ha-llmvision/refs/heads/main/blueprints/event_summary_beta.yaml).

Same problem

```
action: llmvision.image_analyzer
data:
  remember: true
  include_filename: true
  max_tokens: 40
  temperature: 0.5
  image_entity:
    - camera.driveway_camera_snapshots
  provider: 01JDVQW1TKA2N1VJ8AWYSNPQNS
  message: What is happening around the house?
  expose_images: true
  generate_title: true
  use_memory: true
  model: gemini-2.0-flash
  expose_images_persist: true
```
